### ISSUE TITLE
Markdown Navigator cracked, but it still cannot open enhanced edittion.

### ISSUE THREAD

**Issue by pokk** [An0nymous0/MybatisPlugin-Crack-Javassist#2]
I followed your instructions to crack Markdown Navigator, and I succeed, too.

![screen shot 2016-12-19 at 9 16 47](https://cloud.githubusercontent.com/assets/5198104/21297922/ec68163e-c5cb-11e6-8136-5e336a5d0411.png)

Do you know how can I open all of the functions?

![screen shot 2016-12-19 at 9 19 01](https://cloud.githubusercontent.com/assets/5198104/21297945/36c96fe8-c5cc-11e6-85e2-7b35d628814f.png)

**Comment by pokk** [comment]
BTW, the version of Markdown Navigator is 2.2.0

**Comment by An0nymous0** [comment]
@pokk Has been resolved，See commit：https://github.com/An0nymous0/MybatisPlugin-Crack-Javassist/commit/d1a8a072f059840b6e16f037a4e284095f7b9a4f
