### ISSUE TITLE
关于PR 

### ISSUE THREAD

**Issue by xiaolongyuan** [An0nymous0/MybatisPlugin-Crack-Javassist#5]
兄弟 开源是一个松散的组织 没有条款是因为一个人做错了某件事就剔除一个人的
而且也并不是不痛不痒道歉大家就接受的  至少在我看来我不会接受 虽然怼的不是我 
只是希望少点戾气  不要因为这个PR 又掀起新一轮互怼 事实上微博已经怼起来了 各种不理性 

![image](https://user-images.githubusercontent.com/3142363/29013193-f07bb970-7b73-11e7-87c3-8594876aa30a.png)
http://weibo.com/1748374882/FfXarDQPi?type=comment&pcfrom=msgbox

![image](https://user-images.githubusercontent.com/3142363/29013246-59fd37fc-7b74-11e7-84a9-73850f6417fa.png)

http://weibo.com/1401880315/FfWYGmqTS?type=comment

**Comment by An0nymous0** [comment]
不是想怼，VUE官方的大度以及理性接受道歉是绝对正确的做法，但是并不一定可以纠正这个事情，就好比上下属关系的两个人会互相搪塞一样，因为是迫不得已，但是如果第三方插足就不一样了，没想到的是其他人都在学习模仿官方的态度。如果集体去反对这样的人让下一个想要做这种事情的人会产生犹豫或者知道自己做了可能会付出代价，我想更好。让每一篇文章都是理性分析，比较优点与劣势，而不是比较好与坏一票否决。 这种环境下只会让小白迷惘在前端这种恶心的环境中。怼这个事本来就没什么意义，而且我说的这个事其实跟vue和angular也没有直接关系，主要是风气问题。开源哪都能松散，但是如果恶意竞争这一环节出现问题，还怎么开源了，优秀项目都会被软文覆盖。

**Comment by xiaolongyuan** [comment]
这问题无解
现在angular官方也参与进来了 看进一步的事件导向吧
