### ISSUE TITLE
最新更新的mybatis plus 3.13版本求破解啊

### ISSUE THREAD

**Issue by shuohao** [An0nymous0/MybatisPlugin-Crack-Javassist#6]
把报名代码什么的都混淆了

**Comment by An0nymous0** [comment]
不但混淆了，代码架构也变了，源码都跟原来不一样了。 找到破解方法需要时间。

**Comment by shuohao** [comment]
这个破解难度感觉特别大 主要是卖的太贵了$69.99，要不然也就支持了

**Comment by An0nymous0** [comment]
@shuohao https://github.com/An0nymous0/MybatisPlugin-Crack-Javassist/issues/7
